apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        demo: k8s-handson
    spec:
      containers:
      - name: nginx-server
        image: ramaraja/webserver
        imagePullPolicy: IfNotPresent

  replicas: 3
  selector:
    matchLabels:
      demo: k8s-handson
